databases:
  - name: google-form-db
    plan: free

services:
  - type: web
    name: google-form
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: google-form-db
          property: connectionString
